export const SAVE = 'SAVE'
export const FIND_ALL_WIDGETS = 'FIND_ALL_WIDGETS'
export const DELETE_WIDGET = 'DELETE_WIDGET'
export const ADD_WIDGET = 'ADD_WIDGET'
export const HEADING_SIZE_CHANGED = 'HEADING_SIZE_CHANGED'
export const SELECT_WIDGET_TYPE = 'SELECT_WIDGET_TYPE'
export const HEADING_TEXT_CHANGED = 'HEADING_TEXT_CHANGED'

export const PARAGRAPH_TEXT_CHANGED = 'PARAGRAPH_TEXT_CHANGED'
export const WIDGET_NAME_CHANGED = 'WIDGET_NAME_CHANGED'
export const FIND_ALL_WIDGETS_FOR_TOPIC = 'FIND_ALL_WIDGETS_FOR_TOPIC'

export const LIST_TEXT_CHANGED = 'LIST_TEXT_CHANGED'
export const LIST_ORDER_CHANGED = 'LIST_ORDER_CHANGED'

export const IMAGE_TEXT_CHANGED = 'IMAGE_TEXT_CHANGED'
export const IMAGE_URL_CHANGED = 'IMAGE_URL_CHANGED'

export const LINK_TEXT_CHANGED = 'LINK_TEXT_CHANGED'
export const LINK_URL_CHANGED = 'LINK_URL_CHANGED'

export const MOVE_UP = 'MOVE_UP'
export const MOVE_DOWN = 'MOVE_DOWN'

export const PREVIEW = 'PREVIEW'

